### PR TITLE
Add node-gyp to README

### PR DESCRIPTION
**Pull request by MichaelAquilina**
Running rebuild would not work for me unless `node-gyp` was installed. This is pretty confusing to debug since no output is produced by the `rebuild` task.

### CODE REVIEW

**Comment by Aluxian** [comment]
Thanks!

But I don't think it should be added in the dependencies section like `gulp`. It's not a mandatory package, it's only for those who don't have it already (to be honest, I never had to manually install it, so I don't understand why you had to – but I'm assuming I had it installed some other way).

Can you please add that step separately? Something like:

```
If rebuilding doesn't work, make sure you have node-gyp installed:
npm install -g node-gyp
```

**Comment by MichaelAquilina** [comment]
Wouldn't a failing build without it mean that it is essentially mandatory though?

**Comment by Aluxian** [comment]
It would, indeed.

But what if most people *don't* need to install it explicitly? I don't want to make them install it this way – not because I know it'd harm them, but because I don't know if it won't do any harm.

**Comment by MichaelAquilina** [comment]
Are you referring to the case were they would have it installed from a previous project?

**Comment by Aluxian** [comment]
> npm bundles its own, internal, copy of node-gyp. This internal copy is independent of any globally installed copy of node-gyp that you may have installed via npm install -g node-gyp.

https://github.com/nodejs/node-gyp/wiki/Updating-npm's-bundled-node-gyp

Here, I found some proof to defend my assumption that we shouldn't ask everyone to install node-gyp.

**Comment by MichaelAquilina** [comment]
Interesting, so why would my copy of node not have this? Is this a packaging dependent thing? I installed node from Ubuntu 16.04 standard repositories for example.

**Comment by Aluxian** [comment]
I don't know, maybe npm failed to install node-gyp but didn't notify you.

**Comment by MichaelAquilina** [comment]
so you are right that npm installs `node_gyp`  along with itself. Checking the the contents of `apt-file` proves this:
```
apt-file show npm|grep -E "node-gyp$"
npm: /usr/share/npm/node_modules/.bin/node-gyp
```
I wonder if this is actually a bug in how npm is setup on Ubuntu?

**Comment by MichaelAquilina** [comment]
Is the version important?
```
$ # Whats included with the npm package
$ /usr/share/npm/node_modules/.bin/node-gyp --version
v3.2.1
$ # Whats installed with with npm install -g node-gyp
$ node-gyp --version      
v3.4.0
```

**Comment by Aluxian** [comment]
I don't think so

**Pull request closed without merging**
