### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by mrl4214**
I build an AUR package for whatsie for ease of installation/updating on Arch Linux. It's very easy to maintain and I'm happy to do it because I use whatsie everyday.

### CODE REVIEW

**Comment by Aluxian** [comment]
Hey, what do you think if we integrated this into the CI build script ([this file](https://github.com/Aluxian/Whatsie/blob/master/circle.yml))? You wouldn't have to maintain it yourself, and the package would be built and updated automatically for each release.

- What are the steps to build the AUR package?
- Are there any node.js solutions (if not, we can just spawn another tool from node)?

This is what we'd have to do in order to integrate building the AUR package into the current workflow:
- add a task in `tasks/pack.coffee` to create the AUR package
- add a task in `tasks/publish.coffee` to upload the package to https://aur.archlinux.org/packages/
- add the commands to `circle.yml` to run the tasks defined above

I'd really appreciate if you could send a PR for this or just give it a try because I'm already busy with some fairly important bugs. I'm ready to assist you via [Gitter](https://gitter.im/Aluxian/Whatsie), Telegram, [email or Facebook](http://www.aluxian.com/#contact) :)

**Comment by mrl4214** [comment]
I'd love to do that. What's your telegram?

**Comment by Aluxian** [comment]
Awesome! https://telegram.me/aluxian

**Comment by mrl4214** [comment]
Just FYI AUR does handle updates. I'll push out the new release in 20 minutes to AUR

**Pull request merged**
