### PR TITLE
Add NumixDark theme

### PR DESCRIPTION
**Pull request by MichaelAquilina**
Adds a Numix Dark theme which blends nicely into a GTK3 environment with Numix enabled.

See https://satya164.github.io/numix/#branding

### CODE REVIEW

**Comment by MichaelAquilina** [comment]
Not sure what the failure is? Could we try a rebuild?

**Comment by Aluxian** [comment]
Builds are not configured appropriately for PRs at the moment. It's something I have to get right. Anyway, the error is not in your code, but that it could not upload the assets to GitHub Releases.

**Comment by MichaelAquilina** [comment]
Hey @Aluxian any feedback on this? :)

**Comment by MichaelAquilina** [comment]
Here's an example of what the theme looks like Whatsie Numix Dark Theme

**Comment by Aluxian** [comment]
That looks awesome! I think it's one of the most beautiful themes, thank you <3

**Comment by Aluxian** [comment]
I'm testing a new build right now, 2.0.15-dev. After I release this I'll merge the PRs.

**Comment by MichaelAquilina** [comment]
awesome, thanks! :+1:

**Pull request merged**
