### PR TITLE
[WIP] Pretty settings

### PR DESCRIPTION
**Pull request by levrik**
**THIS PR IS WORK IN PROGRESS!**

This is a prototype for a custom settings view within the WhatsApp Web settings.
The settings are not usable for now and the initial values are hardcoded and not read from the user.

Now my questions: Do you want something like that or not and, if yes, how can I connect this with the real existing settings logic?

### CODE REVIEW

**Comment by levrik** [comment]
GIF demonstrating this PR

**Comment by Aluxian** [comment]
Wow, that looks awesome! However, I don't have any more time to work on Whatsie and I'm focusing on MFD now.

If you're able to send a complete PR, I might make some time to test it and push the update.

You can see how the menu works right now by looking into src/scripts/menu. Basically, every menu item is assigned a handler. Handlers are actually compositions of smaller functions ("expressions").

**Comment by levrik** [comment]
@Aluxian It could take some time, but I will try it :)

**Comment by levrik** [comment]
@Aluxian Really sad that this project died. I will close this PR since it's not necessary anymore.

**Pull request closed without merging**
