### PR TITLE
Ability to download profile pictures

### PR DESCRIPTION
**Pull request by levrik**
This PR adds the ability to download profile pictures which is (currently) not implemented in WhatsApp Web. Does not work on group chats for now.

Demonstration in this GIF:

### CODE REVIEW

**Comment by Aluxian** [comment]
Nice work with the observers!

**Comment by levrik** [comment]
@Aluxian Thanks :smiley: I actually wanted to observe the image viewer, but the container don't get a class name attached so I have to use a click handler on the profile picture preview on the info panel.

**Comment by Aluxian** [comment]
Here's how I improved it: https://github.com/Aluxian/Whatsie/commit/6490cdf519ab35ccce95eeec4d2abd06ae7abf38

**Comment by levrik** [comment]
Very nice!

**Pull request merged**
